#!groovy

// Generated by IBM TransformationAdvisor
// Fri Mar 22 15:42:04 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}