#!groovy

// Generated by IBM TransformationAdvisor
// Thu Mar 21 14:32:01 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}